### ISSUE TITLE
Thanks for your great contribution ：）

### ISSUE THREAD

**Issue by lucywsq** [skyzh/skyzh#1]
2021/12/09 Update: I sincerely apologize for abusing the github issue system and we’ll find more proper ways to communicate with contributors in the future.

~Hi skyzh 
We are so appreciative of your contribution to fixing pylint rules through the “Let’s become Taichi contributors within 10 minutes” program. Please send an email to siqiwu@taichi.graphics with your offline address. We would deliver a hoodie to you. : ) Looking forward to hearing from you!~

~非常感谢您参与第0次十分钟成为 Taichi contributors 活动，并在 pylint 命令修复中的宝贵贡献！ 为表感谢，近期太极周边会向你赶来～请麻烦将收件信息发送至运营同学 siqiwu@taichi.graphics 欢迎持续关注 Taichi 社区哦～
Taichi 开源社区 敬上~

**Comment by skyzh** [comment]
GitHub issue is never a place for personal chat and private message. Using GitHub issue as a message box is really a bad idea -- I have never seen any open source community doing things like this, this is really bad. Please only report *issues* here.

By the way, I have already contacted you on WeChat. Anyway, thanks for your recognization from Taichi community.

**Comment by skyzh** [comment]
And I believe such message can be considered a kind of spam and you will be banned from using GitHub if anyone reports your misbehavior to GitHub, even though I did't report this. Please refer to the [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

> Be clear and stay on topic - People use GitHub to get work done and to be more productive. Off-topic comments are a distraction (sometimes welcome, but usually not) from getting work done and being productive. Staying on topic helps produce positive and productive discussions.

> Disrupting the experience of other users
>
> Being part of a community includes recognizing how your behavior affects others and engaging in meaningful and productive interactions with people and the platform they rely on. Behaviors such as repeatedly posting off-topic comments, opening empty or meaningless issues or pull requests, or using any other platform feature in a way that continually disrupts the experience of other users are not allowed. While we encourage maintainers to moderate their own projects on an individual basis, GitHub staff may take further restrictive action against accounts that are engaging in these types of behaviors.

I don't think you are a qualified user for having proper communication on GitHub. Please do contact your developer colleagues and ask for their advice for such behaviors in the future.

@lucywsq

**Comment by skyzh** [comment]
For me, skyzh/skyzh repo is somewhat a place to discuss. Personally I would be okay with this, but this is not welcomed. However, it is even improper of you to report unrelated issues in other users' project:

https://github.com/MarkHershey/hackintosh-project/issues/1
https://github.com/DeepDuke/ros_sort_tracker/issues/2
https://github.com/Lyken17/tumi/issues/1
https://github.com/IceCodeNew/Guides/issues/1
https://github.com/mosecorg/mosec/issues/95
https://github.com/ZonePG/zonepg.github.io/issues/1
https://github.com/Dustyposa/goSpider/issues/1
https://github.com/LJHG/wiki/issues/1

I don't see any relation between "Thanks for your great contribution" in Taichi community with any of the projects mentioned above. From my perspective, this is more than improper -- posting completely unrelated issues on such projects is *spamming*.

**Comment by k-ye** [comment]
Hi there,

I'm Ye, an early contributor and maintainer of the Taichi project. I sincerely apologize for this spam misbehavior and the consequence.

We acknowledge that posting issues that are irrelevant to personal/organizational GitHub repos is a breach to the community's code of conduct and deemed unprofessional. We will close all similar issues (BTW, thanks for compiling the list in https://github.com/skyzh/skyzh/issues/1#issuecomment-988952674!), release more of our technical roadmaps and make sure our community is mostly techincal oriented.

Going forward, if you find anything unprofessional in our community operations, just shoot me a message at yekuang_at_taichi.graphics :-) 

Best,
Ye

**Comment by Lyken17** [comment]
Seesm the action is mis-performed by some scripts / CIs? 

I was bit surprised when seeing the `thanks note` in my personal repo.  While I agree this is improper to use issue as the mailbox for un-related messages, this is not as serious as spamming to me. It is more like a mis-operation rather than intended offense.  A better way to send gifts would be @ everyone in the original thread. Please do not abuse the issue function in the future.
